inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "node_modules/**/*"
    - "vendor/**/*"

Metrics/BlockLength:
  Exclude:
    - "config/environments/*.rb"
    - "config/initializers/**/*.rb"
    - "config/routes.rb"
    - "lib/tasks/**/*.rake"

Layout/LineLength:
  Max: 120
  AllowHeredoc: true
  AllowURI: true
  AllowedPatterns:
    - '^\s*#'
  Exclude:
    - "config/initializers/devise.rb"
