inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  TargetRubyVersion: 3.2
  NewCops: disable
  Exclude:
    - "db/schema.rb"
    - "vendor/**/*"
    - "bin/**/*"
    - "node_modules/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Rails/I18nLocaleTexts:
  Enabled: false

Layout/HashAlignment:
  Enabled: false
Layout/EmptyLines:
  Enabled: false
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
Style/Lambda:
  Enabled: false
Lint/UnusedBlockArgument:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false
