plugins:
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  Exclude:
    - "bin/**/*"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "db/schema.rb"

Style/Documentation:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: true

Layout/LineLength:
  Max: 120
  Exclude:
    - "config/initializers/**/*.rb"

Metrics/BlockLength:
  Exclude:
    - "config/environments/**/*.rb"
    - "config/initializers/**/*.rb"
    - "db/migrate/**/*.rb"

Rails/NotNullColumn:
  Exclude:
    - "db/migrate/**/*"
