databases:
  - name: rails-project-64-db
    plan: free

services:
  - type: web
    name: rails-project-64
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server -p $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails-project-64-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: BUNDLE_WITHOUT
        value: "development:test"
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
