name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
          bundler-cache: true

      - name: Set up Node (for jsbundling/cssbundling)
        uses: actions/setup-node@v5
        with:
          node-version: "20"

      - name: Install JS deps
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi

      - name: Lint (Rubocop + Slim)
        run: |
          bundle exec rubocop --parallel
          bundle exec slim-lint app/views

      - name: Prepare DB
        run: bin/rails db:prepare

      - name: Run tests (minitest)
        run: bin/rails test
